export const HARDCODED_CATEGORIES = [
  "Ceramic Vases",
  "Glass Vases",
  "Vessels",
  "Others Vase",
  "Animal Figure",
  "Human Figure",
  "Plant Figure",
  "Others Figure",
  "Sculpture",
  "BOOKED",
  "CANDLE HOLDERS",
  "Box",
  "Trays",
  "Toy",
  "Lamp",
  "Flower",
  "Plates & Dishes",
  "Bowls",
  "Glassware",
  "Cups & Mugs",
  "Trays & Servingware",
  "Other Dining & Tableware",
  "Bath Room",
  "Dressing Room",
  "Handmade",
  "3D Handmade",
  "Digital print",
  "Mixed Media Art",
  "Others Art & walldecor",
  "Photo Frame"
];

// Keep display names separate from fullValue so existing URLs and filters remain stable.
export const CATEGORY_DISPLAY_NAMES: Record<string, string> = {
  "VASE & VESSELS": "Vase & Vessels",
  "Ceramic Vases": "Ceramic Vases",
  "Glass Vases": "Glass Vases",
  "Vessels": "Vessels",
  "Others Vase": "Others Vase",

  "FIGURE": "Figure",
  "Animal Figure": "Animal Figure",
  "Human Figure": "Human Figure",
  "Plant Figure": "Plant Figure",
  "Others Figure": "Others Figure",

  "Sculpture": "Sculpture",
  "SCULPTURE": "Sculpture",
  "BOOKED": "Booked",
  "CANDLE HOLDERS": "Candle Holders",

  "ACCESSORIES": "Accessories",
  "Box": "Box",
  "Trays": "Trays",
  "Toy": "Toy",
  "Flower": "Flower",
  "FLOWER": "Flower",
  "Vase and Flower": "Flower",
  "Lamp": "Lamp",
  "LAMP": "Lamp",
  "Lamp (โคมไฟ)": "Lamp",

  "DINING & TABLEWARE": "Dining & Tableware",
  "Plates & Dishes": "Plates & Dishes",
  "Bowls": "Bowls",
  "Glassware": "Glassware",
  "Cups & Mugs": "Cups & Mugs",
  "Trays & Servingware": "Trays & Servingware",
  "Other Dining & Tableware": "Other Dining & Tableware",

  "DRESSING & BATH": "Dressing & Bath",
  "Bath Room": "Bath Room",
  "Dressing Room": "Dressing Room",

  "ART & WALL DECOR": "Art & Wall Decor",
  "Handmade": "Handmade",
  "3D Handmade": "3D Handmade",
  "Digital print": "Digital Print",
  "Mixed Media Art": "Mixed Media Art",
  "Photo Frame": "Photo Frame",
  "Others Art & walldecor": "Others Art & Wall Decor",
  "OTHERS ART & WALL DECOR": "Others Art & Wall Decor",
  "Others Art & Walldecor": "Others Art & Wall Decor",
  "Others Art & walldecor (ตกแต่งผนังอื่น ๆ)": "Others Art & Wall Decor",

  "IN_STOCK": "In Stock",
  "READY_TO_SHIP": "Ready To Ship",
  "UNCATEGORIZED": "Other (ยังไม่มีในหมวดข้างต้น)",
  "UNMAPPED": "Other (ยังไม่มีในหมวดข้างต้น)",

  // Legacy mappings for bookmarks/old links
  "Art Object": "Ornament",
  "Book End": "Bookends",
  "Candle Holder": "Candle Holders",
  "Decorative": "Accessories",
  "Doll": "Figure",
  "Kitchenware": "Dining & Tableware",
  "Tray": "Trays",
  "Vase": "Vase & Vessels",
  "Wall Art": "Art & Wall Decor",
};
